version: "3.8"

volumes:
  backend-node-modules:
  frontend-node-modules:

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/app:/app
      - backend-node-modules:/app/node_modules
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/app:/app
      - frontend-node-modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true # ホットリロードの設定
    networks:
      - app-network

networks:
  app-network:
    driver: bridge